name: iOS Manual Test

on:
  workflow_dispatch:

jobs:
  check-swift:
    name: Check Swift
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show Xcode and Swift version
        run: |
          xcodebuild -version
          swift --version

  check-project:
    name: Check Project
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List project info
        run: |
          xcodebuild -list -project workflow_demo.xcodeproj
